// This file is automatically generated. DO NOT EDIT.
//
// Positive control -- NOT a false positive. The auto-generated-file signal (Bug A,
// signal b) is deliberately scoped to values that ALSO look like snake_case DB
// identifiers (looksLikeGeneratedDbIdentifier) -- a real secret accidentally checked
// into a generated file (a codegen template with a hardcoded default credential does
// happen) must still be flagged. Prefixed with an underscore so it sorts away from the
// actual false-positive fixtures and is unmistakably a control.

export const debugApiKey = "aB3xQ9mZ7pL2vN8jT1cR6wY3bH5fD0sU4gK";
