// This file is automatically generated by the ORM codegen step. DO NOT EDIT.
//
// Companion case to supabase-generated-types-fkey.ts: exercises the SECONDARY signal
// (an auto-generated file header + a snake_case, DB-identifier-shaped value) rather than
// the primary "*KeyName" property-name signal. `relationKey` does NOT end in a recognized
// "*Name" suffix (KeyName/ConstraintName/IndexName), so signal (a) alone would not catch
// it -- only the file-header + value-shape combination does.

export const relationMeta = {
  relationKey: "orders_customer_id_fkey_relation_meta",
};
